### ISSUE TITLE
dfu programmer without root linux

### ISSUE THREAD

**Issue by ricardolima91** [dfu-programmer/dfu-programmer#38]
Hi guys. I use the dfu in Windows and mac and dont need any type of permission. Just run and its ok.
Now in ubuntu i'am facing some problems because i cant run it with sudo.. We can do any trick to pass this ? I already tried the parameter usbcore autosuspend = -1 but still the same .. 
I really need to run it without sudo because i'am doing that behind a app.
Thank you in advance

**Comment by EspoTek** [comment]
You'll need to set up a udev rule for your device in order to give libusb read/write access.

Here's a sample I use for the ATXMega32A4U in my software:
ENV{ID_VENDOR_ID}=="03eb", ENV{ID_MODEL_ID}=="2fe4", SYMLINK="ATXMEGA32A4U DFU Bootloader", MODE="0666"

Just change the bit that says "2fe4" to the appropriate PID for your device and you're done.
